//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int IdBiletu { get; set; }
        public int IdSeansu { get; set; }
        public int IdMiejsca { get; set; }
        public int IdTypuBiletu { get; set; }
        public decimal Cena { get; set; }
        public decimal Rabat { get; set; }
        public System.DateTime DataSprzedazy { get; set; }
        public bool CzyAnulowany { get; set; }
        public bool CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public bool CzyOplacony { get; set; }
    
        public virtual MiejsceWSali MiejsceWSali { get; set; }
        public virtual TypBiletu TypBiletu { get; set; }
        public virtual Seans Seans { get; set; }
    }
}
