//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dystrybutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dystrybutor()
        {
            this.Film = new HashSet<Film>();
        }
    
        public int IdDystrybutora { get; set; }
        public string Nazwa { get; set; }
        public int IdKraju { get; set; }
        public string Email { get; set; }
        public bool CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string TelefonKontaktowy { get; set; }
        public string ModelRozliczen { get; set; }
        public Nullable<decimal> ProcentProwizji { get; set; }
        public bool CzyUmowaPodpisana { get; set; }
        public string NumerUmowy { get; set; }
        public Nullable<System.DateTime> UmowaOd { get; set; }
        public Nullable<System.DateTime> UmowaDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film> Film { get; set; }
        public virtual Kraj Kraj { get; set; }
    }
}
