//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Seans = new HashSet<Seans>();
        }
    
        public int IdFilmu { get; set; }
        public string Tytul { get; set; }
        public string TytulOryginalny { get; set; }
        public string Opis { get; set; }
        public int CzasTrwania { get; set; }
        public int RokProdukcji { get; set; }
        public Nullable<System.DateTime> DataPremiery { get; set; }
        public string UrlPlakatu { get; set; }
        public int IdStatusuFilmu { get; set; }
        public int IdKategoriiWiekowej { get; set; }
        public int IdDystrybutora { get; set; }
        public bool CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public int IdJezykaOryginalnego { get; set; }
        public int IdGatunku { get; set; }
        public int IdProducenta { get; set; }
        public int IdRezysera { get; set; }
        public int IdKraju { get; set; }
    
        public virtual Dystrybutor Dystrybutor { get; set; }
        public virtual KategoriaWiekowa KategoriaWiekowa { get; set; }
        public virtual StatusFilmu StatusFilmu { get; set; }
        public virtual Jezyk Jezyk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seans> Seans { get; set; }
        public virtual GatunekFilmu GatunekFilmu { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Rezyser Rezyser { get; set; }
        public virtual Kraj Kraj { get; set; }
    }
}
