//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiejsceWSali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MiejsceWSali()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int IdMiejsca { get; set; }
        public int IdSali { get; set; }
        public int Rzad { get; set; }
        public int Numer { get; set; }
        public string TypMiejsca { get; set; }
        public bool CzyAktywne { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
