//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PABProjektEntities : DbContext
    {
        public PABProjektEntities()
            : base("name=PABProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Dystrybutor> Dystrybutor { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<GatunekFilmu> GatunekFilmu { get; set; }
        public virtual DbSet<Jezyk> Jezyk { get; set; }
        public virtual DbSet<KategoriaWiekowa> KategoriaWiekowa { get; set; }
        public virtual DbSet<Kraj> Kraj { get; set; }
        public virtual DbSet<MiejsceWSali> MiejsceWSali { get; set; }
        public virtual DbSet<Producent> Producent { get; set; }
        public virtual DbSet<Rezyser> Rezyser { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<StatusFilmu> StatusFilmu { get; set; }
        public virtual DbSet<StatusSeansu> StatusSeansu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypBiletu> TypBiletu { get; set; }
        public virtual DbSet<TypEkranu> TypEkranu { get; set; }
        public virtual DbSet<TypNaglosnienia> TypNaglosnienia { get; set; }
        public virtual DbSet<TypSali> TypSali { get; set; }
        public virtual DbSet<Seans> Seans { get; set; }
    }
}
