//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sala()
        {
            this.MiejsceWSali = new HashSet<MiejsceWSali>();
            this.Seans = new HashSet<Seans>();
        }
    
        public int IdSali { get; set; }
        public int NumerSali { get; set; }
        public int LiczbaMiejsc { get; set; }
        public int IdKina { get; set; }
        public int IdTypuEkranu { get; set; }
        public int IdTypuNaglosnienia { get; set; }
        public int IdTypuSali { get; set; }
        public bool CzyAktywna { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public string Uwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiejsceWSali> MiejsceWSali { get; set; }
        public virtual TypEkranu TypEkranu { get; set; }
        public virtual TypNaglosnienia TypNaglosnienia { get; set; }
        public virtual TypSali TypSali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seans> Seans { get; set; }
    }
}
