//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDABProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seans()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int IdSeansu { get; set; }
        public int IdFilmu { get; set; }
        public int IdSali { get; set; }
        public int IdStatusuSeansu { get; set; }
        public bool CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public string KtoModyfilowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
        public int IdJezyka { get; set; }
        public bool CzyNapisy { get; set; }
        public bool CzyLektor { get; set; }
        public bool CzyDubbing { get; set; }
        public System.DateTime DataSeansu { get; set; }
        public System.TimeSpan GodzinaOd { get; set; }
        public System.TimeSpan GodzinaDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Film Film { get; set; }
        public virtual Jezyk Jezyk { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual StatusSeansu StatusSeansu { get; set; }
    }
}
